/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  User200Response,
} from '../models/index';
import {
    User200ResponseFromJSON,
    User200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class UserControllerApi extends runtime.BaseAPI {

    /**
     */
    async userRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<User200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/user/profile`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => User200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async user(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User200Response> {
        const response = await this.userRaw(initOverrides);
        return await response.value();
    }

}
