/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User200Response
 */
export interface User200Response {
    /**
     * 
     * @type {string}
     * @memberof User200Response
     */
    name?: string;
}

/**
 * Check if a given object implements the User200Response interface.
 */
export function instanceOfUser200Response(value: object): value is User200Response {
    return true;
}

export function User200ResponseFromJSON(json: any): User200Response {
    return User200ResponseFromJSONTyped(json, false);
}

export function User200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): User200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function User200ResponseToJSON(json: any): User200Response {
    return User200ResponseToJSONTyped(json, false);
}

export function User200ResponseToJSONTyped(value?: User200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

