apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: spring-boot
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/data/db-pv 